---
name: Bundle-Modules
version: 2006.0524
author:
  - 'Eric R. Meyers <ermeyers@adelphia.net>'
abstract: Interface to bundle modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.6.1
build_requires:
  Test::More: 0
recommends:
  Test::Memory::Cycle: 0
  Test::Pod: 0
  Test::Taint: 0
  Test::Warn: 0
provides:
  Bundle::Modules:
    file: lib/Bundle/Modules.pm
    version: 2006.0524
  Bundle::Modules::Acme::Everything::Unique:
    file: lib/Bundle/Modules/Acme/Everything/Unique.pm
    version: 2006.0524
  Bundle::Modules::Acme::Everything::Unique::Unstable:
    file: lib/Bundle/Modules/Acme/Everything/Unique/Unstable.pm
    version: 2006.0524
  Bundle::Modules::Apache:
    file: lib/Bundle/Modules/Apache.pm
    version: 2006.0524
  Bundle::Modules::Apache::Unstable:
    file: lib/Bundle/Modules/Apache/Unstable.pm
    version: 2006.0524
  Bundle::Modules::CPAN:
    file: lib/Bundle/Modules/CPAN.pm
    version: 2006.0524
  Bundle::Modules::CPAN::Unstable:
    file: lib/Bundle/Modules/CPAN/Unstable.pm
    version: 2006.0524
  Bundle::Modules::Test::Reporter:
    file: lib/Bundle/Modules/Test/Reporter.pm
    version: 1.27
  Bundle::Modules::Unstable:
    file: lib/Bundle/Modules/Unstable.pm
    version: 2006.0524
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
