package Bundle::Modules::Acme::Everything;

use 5.005;

our $VERSION = 2006.0519; ## (YYYY.MMDD)

1;

__END__

=head1 NAME

Bundle::Modules::Acme::Everything - All current I<stable> modules in Bundle::Modules::Acme::Everything

=head1 SYNOPSIS

perl -MCPAN -e B<'install Bundle::Modules::Acme::Everything'>

cpan B<-i Bundle::Modules::Acme::Everything>

=head1 CONTENTS

Lingua::ZH::CEDICT
Win32::Filenames
Math::Random
Authen::Users
HtDig::Htsearch
Sendmail::AccessDB
X11::Wcl
Net::Whois::IP
WING
Class::PublicInternal
Lingua::Treebank
Tie::Cycle
XML::PYX
Time::Object
Math::ErrorPropagation
XML::XQL
Lingua::DE::Wortschatz
POE::Component::IRC::Onjoin
Bundle::Perl6
Lingua::FR::Numbers
PDF
Text::SimpleTemplate
Authen::PAM
SWIFT::Factory::Tag::Tag20
Tie::Hash::Regex
Class::ObjectTemplate::DB
Data::MaskPrint
IO::Stty
Convert::TNEF
String::DiffLine
Tk::DynaTabFrame
Net::Daemon::SSL
HTML::Chunks::Super
News::Newsrc
End
Mail::Sort
Term::Query
HTML::Mason
File::CounterFile
Net::IPP
Games::Cards::Poker
Parse::PlainConfig
VMS::User
CGI::FormManager
CGI::Ajax
Replication::Recall::Client
XML::TreeBuilder
No::Sort
Class::DataStore
Lingua::ZH::Summarize
Filesys::mntent
Date::Easter
String::Buffer
CGI::Out
JavaScript::Squish
Lingua::Romana::Perligata
DbFramework::DataType
Text::Wrap::Hyphenate
Locale::PGetText
List::Util
ERG
Tie::RDBM
Archive::Tar
Heap
Ptty
Class::NamedParms
I18N::Charset
Fame
Math::SymbolicX::Inline
Net::Netrc
DBD::Ingres
Parse::Yapp
Business::ISBN
Exporter::Import
Parallel::ForkManager
Lingua::Identify
Pod::POM
Tie::AliasHash
DWH_File
SWIFT::Factory::Tag::Tag17T
DBIx::SQLEngine
Crypt::TripleDES
Geography::States
DNS::Config
Games::Alak
Tk::ObjEditorDialog
Crypt::Noekeon
Shell::Source
X11::Fvwm
Bryar::DataSource::SVNRepos
Devel::LeakTrace
Imager::TimelineDiagram
Persistent::MySQL
Tk::TIFF
Getopt::Help
Search::ContextGraph
NexTrieve::Docseq
HTML::Base
SCGI
Net::Packet
Authen::SASL
MIME::Lite::TT
TiVo::HME
Lingua::EN::NameParse
Mac::Types
MSSQL::Sqllib
Math::Spline
MIME::Lite
GD
Audio::Play::MPG321
Attribute::Overload
Speech::Festival::Synthesiser
Win32::FetchCommand
Devel::StackTrace
List::Rotation::Cycle
Puppet::VcsTools::File
CGI::Formalware
Make
CGI::XML
XML::Filter::DetectWS
AsciiDB::TagFile
String::Scanf
ASP
Data::Traverse
Oracle::Trace
Win32API::Registry
Mail::Toaster
Python::Err
Error
Mail::Internet
Array::Compare
Statistics::LTU
GSS
namespace
LWP::Conn
SAP::Rfc
Hey::heyPass
RTSP::Lite
Alien
IPC::ChildSafe
Text::Orientation
Postgres
Tk::Wizard
Text::Similarity
Getopt::Declare
DateTime
MVS::VBFile
Math::SigFigs
WWW::Google::PageRank
Mail::Maildir
Sybase::BCP
Net::RTSP
Math::Fractal::Curve
Log::WithCallbacks
GISI
SWIFT::Factory::Tag::Tag17
Class::ObjectTemplate
Emacs
Mail::CheckUser
Pod::LaTeX
Business::AU::ACN
Socket6
Spreadsheet::WriteExcel
SLOOPS
Debug::Trace
Religion
Net::SMS::MessageNet
XML::Xerces
File::sudoers
Mac::Components
Frontier::RPC
Digest::EMAC
Regexp::Common
DBM::DBass
Getopt::Long::Descriptive
TeX::Hyphen
Test::Unit
WWW::Mail::Hotmail
ElectricArc
Crypt::X509
HTTP::Cookies::Mozilla
Number::Phone::US
WWW::Statistics
URI::Find
Net::DNS::Check
Python::Object
Math::XOR
BoxBackup
File::CacheDir
Remedy::AR
PHP::Session
Maypole::Plugin::Authorization
Tk::LineNumberText
Syntax::Highlight::Shell
MonetDB::CLI::MapiPP
AFS
NexTrieve::MIME
CLucene
Proc::ExitStatus
DBIx::FullTextSearch
WWW::Patent::Page
RPC::PlServer
SGMLS
RPM::Headers
Data::All
Attribute::Abstract
Net::DLookup
SOAP::WSDL
XML::Directory
HPUX::LVM
ex::constant::vars
XML::RegExp
Math::Bezier::Convert
Perl6::Interpolators
HTTP::QuickBase
Template::Plugin::Data::HTMLDumper
PDF::Labels
Test::MockTime
Taint::Runtime
Mac::DtfSQL
XML::Merge
DDL::Oracle
Tk::ProgressBar
X11::Auth
Sys::Lastlog
Net::Ident
Math::Approx::Symbolic
SVG::Manual
PostScript::PrinterFontMetrics
HTML::Template::Set
DbFramework::Util
Net::SCP
LEGO::RCX
MIME::Words
Net::Irate
Games::Maze
Net::SNMP::Interfaces
Business::Payroll
Win32::Exchange::SMTP::Security
Lemonldap::Portal
Games::Go::GoPair
Games::Object
Net::servent
Lingua::Stem::Fr
Test::Numeric
Math::Derivative
GMail::Checker
Algorithm::Graphs::TransitiveClosure
Text::Parser
Net::FTPServer
Bio::Affymetrix
Archive::Zip
Sys::Filesystem::Unix
HPUX::Ioscan
Astro::SkyCoords
DBD::Unify
CGI::ArgChecker
HTML::GenToc
Chatbot::RiveScript
Devel::Hints
W3C::LinkChecker
Win32::GUI::HyperLink
Solaris::MapDev
MP3::Mplib
DBIx::SchemaView
Env::Path
DBIx::dbMan
ExtUtils::DynaGlue
Filesys::statfs
NexTrieve::Overview
WWW::Shorten::KUSO
LWP::Protocol
MPEG::ID3v2Tag
Email::AutoReply
IO::LCDproc
Log::Log4perl
Win32::Sound
Scalar::Util
Locale::Language
Net::FTP::Versioning
Text::DoubleMetaphone
Tie::DB_Lock
Term::ProgressBar
Math::FresnelZone
Tie::Toggle
Data::Paginate
Date::Convert::French_Rev
Font::AFM
Test::Data
Penguin
Class::Eroot
POE::Loop::Wx
XML::Filter::Sort
NexTrieve::Hitlist::Hit
Parse::YALALR
Time::DaysInMonth
Lemonldap::Cluster::Status
Pod::Checker
DbFramework::ForeignKey
RTF::Parser
Search::VectorSpace
Tk::ExecuteCommand
Gnome2::VFS
Math::Business::SMA
SICStus
B::Graph
Unix::ConfigFile
XML::Checker
Netscape::Bookmarks
Crypt::Blowfish
DBIx::Lookup::Field
Lingua::ZH::HanConvert
WWW::Search::Go
Net::Interface
Image::Maps::Plot::FromLatLong
Script::Toolbox
Term::Size
OS2::ExtAttr
Class::Modular
Crypt::OTP
Digest::CRC
Net::RULI
Statistics::Gap
Verilog::SigParser
XML::Excel
Array::LineReader
Coy
CGI::Application::Plugin::CompressGzip
CGI::Application::Plugin::Stream
Vonage::Click2Call
Win32::ChangeNotify
HTTP::Request
MARC::Errorchecks
Math::Calc::Euro
PGPLOT
OLE::PropertySet
Math::BigInt::GMP
HTML::TokeParser
Mobile::Wurfl
MonetDB::CLI
Locale::SubCountry
Crypt::GOST
File::Remote
Getopt::Attribute
File::chmod
Tk::CursorControl
Quantum::Superpositions
Math::Random::TT800
PDF::Core
PGPLOT::Simple
Event::tcp
Readonly
X11::Xbae
GD::Graph3d
Time::JulianDay
Business::OnlinePayment::Cybersource
Convert::CharMap
POE::Component::DebugShell
Locale::gettext
FUSE::Server
Set::String
DateTime::Format::Builder
DbFramework::Persistent
CGI::FormFactory
Module::Reload
Sys::Filesystem::Linux
Graph::Reader
Tasks
Tk::WaitBox
Test::Exception
XML::RDB
Class::MethodMapper
Heap::Elem::Num
HTML::SimpleParse
No::Telenor
Acme::Homer
PPM
Lingua::ZH::Wrap
Sub::Curry
Mail::Vacation::LDAP
Chart::GRACE
Date::Manip
EventServer::Functions
Text::Graphics
Authen::Krb4
Tk::PNG
Date::DayOfWeek
Graphics::ColorPicker
Text::Flowchart::Script
IO::Lines
MIME::Decoder
Data::Denter
Lingua::ZH::CCDICT
Net::Domain
Proc::Spawn
Solaris::Disk::SVM
Class::Date
Mail::QmailRemote
Tk::ErrorDump
CORBA::IDLtree
Image::ParseGIF
Mono
Chatbot::Alpha::Sort
XML::GXML
AIX::ODM
Email::Send::SMTP::Auth
Parse::Nessus::ENX
Net::TCP
Net::Telnet::Cisco
Bio::ASN1::EntrezGene
X500::DN
Geo::CountryFlags
Plugin::Language::DML
Math::Telephony::ErlangC
HTML::LinkExtor
WordNet::SenseRelate::TargetWord
Unix::PID
Crypt::OpenSSL::X509
Curses::Application
Class::EHierarchy
Mail::DeliveryStatus::BounceParser
Text::Header
LWP::MediaTypes
WWW::Sucksub::Attila
IPChains
NetPacket::IP
NNML::Server
Getopt::Gnu
AI::Categorize
Decision::ACL
Cobalt::LCD
WWW::Search::Google
Bundle::SSH
Statistics::PointEstimation
Geo::WeatherNOAA
WWW::ShopBot
WWW::Dilbert
Teamspeak
DBI::Format
Graph::Kruskal
Unix::Syslog
WebService::Mappoint
Tk::FcyEntry
Tk::Dial
ShellScript::Env
Sub::Assert
IO::Stringy
Audio::Cuefile::Parser
VCS
PDL
Net::NISPlus
Set::Infinite
Lingua::Alphabet::Phonetic
Mail::Alias
Tk::LCD
HTML::Tooltip::Javascript
OLE::Storage_Lite
Bundle::Bugzilla
XML::Grove
Statistics::Distributions
IPC::Door
Math::Evol
Module::Install
Test::More
Net::Netmask
Lingua::EN::Fathom
Math::Taylor
WWW::Sucksub::Frigo
WWW::Google::SiteMap
Tree::Node
Test::Simple
Bio::MCPrimers
GnuPG
Netscape::Server
Config::Abstract
Mac::Apps::Launch
SGML::Parser::OpenSP
Oraperl
Blatte::Builtins
Locale::KeyedText
Acme::Chef
Sys::Utmp
Heap::Elem::Str
Math::Fraction
Bundle::W3C::Validator
DNS::Zone
Text::Substitute
Text::MetaText
Net::netent
EventServer::Gettimeofday
Crypt::IDEA
Bundle::Gnome2
MIME::Latin1
Tie::Multidim
Class::Clone
Quota
Lingua::Stem::Ru
HTML::Breadcrumbs
Puppet::VcsTools::History
NexTrieve::Message
Language::Basic
Net::POP3
DBIx::TableReferences::MSSQL
Games::Score
Finance::Bank::Commerzbank
HTML::Entities::ImodePictogram
CGI::URI2param
Test::URI
LWPx::ParanoidAgent
File::Rsync
Tie::CPHash
Algorithm::Numerical::Shuffle
Mac::FileSpec::Unixish
File::Which
Linux::LVM
Mail::Util
X11::Motif
Geo::METAR
PostScript::PseudoISO
Net::CyanChat::Server
File::Find::Rule
NexTrieve::PDF
Tie::MmapArray
VMS::Misc
Pod::Parser
SWIFT::Factory::Tag::Tag30T
Locale::Maketext::Gettext
Data::Sync
Crypt::RSA
Date::Handler
ex::override
Filesys::Ext2
EventServer::Signal
Chipcard::CTAPI
PHP
RFID::EPC
CGI::NoPoison
Graphics::MNG
Win32::IIS::Admin
Tk::ObjEditor
ControlX10::CM10
Data::FormValidator::Upload
Tk::TabFrame
Math::Geometry::Planar::Offset
Noid
DBD::Recall
IO::Filter
Dialog
Data::Validate::IP
B::Fathom
Finance::Quote
DBIx::XML_RDB
Pod::PerlPoint
Inline::Files
Graphics::Plotter
Log::Dispatch::ToTk
Text::ASCIITable
Unix::Login
Device::SerialPort
Test::Signature
ex::interface
HTML::Validator
XML::SAXDriver::CSV
HTML::Formatter
Time::Normalize
Locale::Maketext
HTML::FromMail
Digest::Perl::MD5
POE::Component::Enc::Flac
Text::Bib
Chemistry::File::PDB
Tk::TableMatrix
HTTP::Size
Data::Hexdumper
Graph::Writer::VCG
Net::PSYC
Thread::Group
HTTP::GetImages
WWW::URLToys
Log::Dispatch::TkText
AI::Gene::Sequence
MP3::ID3v1Tag
Text::Capitalize
Attribute::Types
DMOZ::ParseRDF
Net::AIM
Class::BlackHole
Data::Search
NexTrieve::RFC822
XML::Clean
Lingua::ZH::TaBE
HTTP::Date
SystemC::Netlist
Class::MakeMethods
OpenCA
PDF::PlainLayout
Term::ReadLine::Gnu
Win32::EventLog
Lemonldap::Portal::Session
Net::CIDR
Wily
Sybase::CTlib
Net::Z3950
Data::Iterator
Games::Sudoku::General
Unicode::String
Win32::NetResource
CSS::SAC
Crypt::DH
PostScript::Graph::Bar
Getopt::Mixed
DBD::mSQL
DBIx::Hash2Table
Statistics::TTest
Mail::Procmailrc
WWW::Search
WWW::Search::HotBot
PostScript::Elements
LWP::UA
PostScript::Graph::Style
Class::Mix
Lemonldap::Portal::Sslsso
Biblio::Citation::Parser
Lingua::RU::Antimat
Data::Buffer
XML::Doctype
PerlIO::locale
Oracle::Schema
RPM::Constants
Variable::Alias
Text::Format
XML::DOM
Devel::CoreStack
ExtUtils::ModuleMaker
DCOP::Amarok::Player
Tie::CharArray
Date::Japanese::Era
Mac::MoreFiles
Test::Env
CGI::Request
CGI::DBTables
Finance::QuoteHist
GISI::SHAPE
Sort::ArbBiLex
Hook::Scope
Net::RGTP
Fwctl
Crypt::Rijndael
XML::Validator::Schema
PPresenter
Tie::Tk::Listbox
HTTP::Cache::Transparent
AI::NeuralNet::SOM
DbFramework::Table
ExtUtils::AutoInstall
Gtk2::MozEmbed
Mail::Cap
Encode::HanExtra
CDDB::Fake
Parse::FixedLength
X500::RDN
Shell::POSIX::Select
Data::Sofu
Lemonolap::Log4lemon
HTTPD::Log::Filter
Mobile::WURFL
Crypt::DES
HTML::HeadParser
Pg
Data::DRef
Digest::MD2
HTTP::Response
OS2::REXX
Class::Holon
DBD::Oracle
Blatte
DBIx::Sequence
PAR
Perl
HTML::StickyForms
Text::MicroMason
Class::Delegate
VMS::System
Algorithm::Line::Bresenham
MIME::Lite::HTML
Tie::StrictHash
CPAN::Search::Lite::Index
Image::Thumbnail
DBD::File
DBD::RDB
Verilog::Pli
CGI::State
Be::Query
NexTrieve::Collection::Index
Class::AutoloadCAN
Class::Fields
NexTrieve::Daemon
Unicode::Map8
Netscape::HistoryURL
Net::SMTP::IPMM
PDL::LinearAlgebra
Db::Ctree
VCS::CMSynergy
Metadata::Base
Pod::PP
Crypt::PasswdMD5
File::Atomic
Des
DateTime::Calendar::Mayan
Filter::decrypt
Win32::FileType
Image::ASCII
Spreadsheet::Read
CGI::Base
Modem::Vgetty
Net::Traceroute6
HTML::CalendarMonthDB
Math::Project
Mail::Sendmail
Verilog::CodeGen
Lingua::GL::Stemmer
Text::Stem
Class::MethodFilter
Tie::GHash
Bundle::Rose
Net::SMS
Statistics::OLS
Win32::Guidgen
Lingua::JA::Number
App::Info
File::Touch
NEXT
Math::Matrix::SVD
Win32::AdminMisc
Astro::FITS::Header
POE::Component::UserBase
List::Util::Superpositions
Template::Plugin::Translit::RU
Math::Business::BlackScholes
SIL::Shoe
Search::Binary
Net::LMTP
SQL::Abstract::Limit
Safe::Hole
DBD::Empress
Sub::Quotelike
Bio::mGen
Crypt::ElGamal
OpenOffice::OODoc
RADIUS::Dictionary
Tk::PathEntry
Filesys::dfent
Solaris::Package
Math::Fibonacci::Phi
Crypt::Camellia
Geo::Coordinates::UTM
Template::Plugin::Config::General
Log::Dispatch
Set::IntSpan
Text::Embed
Authen::Ticket
Class::DBI::Test::TempDB
Filesys::DiskFree
Lemonldap::Crypto
Crypt::Random
Data::Binder
Inline::C
RPC::ONC
BerkeleyDB::Locks
Tk::Gpack
WWW::Search::Feedster
DBIx::BabelKit
POE::Component::Pcap
Test::TempDatabase
VRML::VRML2
Mail::Sender
SVG::Template::Graph
Thread::Pool
Authen::PIN
Net::SMS::BulkSMS
NexTrieve::Index
OS2::PrfDB
Tk::Playlist
Parse::RecDescent
XML::Writer
Text::Iconv
Text::TreeFile
LWP
PostScript::TextBlock
Solaris::Disk::Mnttab
Text::BibTeX
Filesys::DiskUsage
Class::DBI::Template
FCGI::ProcManager
XML::Handler::Composer
Win32::GD
User::pwent
Data::Tabular::Dumper
AudioCD::Mac
Sort::PolySort
DBD::Multiplex
Tie::SortHash
ReleaseAction
Proc::SyncExec
Exporter::Options
IO::Toolkit
Net::Telnet::Cisco::IOS
Rose::DateTime
VMS::Device
POE::Component::Server::HTTP
Net::SSLeay
Finance::Bank::Commonwealth
Proc::Simple
Lingua::EN::Numbers::Ordinate
File::Rename
File::VirtualPath
Time::Duration::sv
Pod::Simple
IO::Tee
SVN::Look
CIPP
Watchdog::Service
Tk::GraphViz
Term::Info
Algorithm::BinPack
Neural
Goo
Filesys::SmbClient
Tk::Menustrip
HTML::PopupTreeSelect::Dynamic
Acme::Wabby
Data::Validate
Encode::HEBCI
Crypt::OpenSSL::RSA
MIME::IO
Lemonldap::Handlers::Generic
Proc::Reliable
Net::Milter
Class::AutoAccess
String::Random
Memoize::ExpireLRU
Module::Install::Skip
DBD::RAM
WebSphere::MQTT::Client
Hash::Case
Inline::Guile
File::Searcher
Business::FedEx::DirectConnect
WebCache::Digest
Devel::RegExp
Lingua::PT::Conjugate
SQL::Translator
Time::Piece::MySQL
Convert::BER
Tie::Cycle::Sinewave
CGI::SimpleCache
Crypt::SaltedHash
MARC
Gtk2
PDF::Reuse
Tree::DAG_Node
Tree
Net::Server
Set::Hash
PostScript::Metrics
Encode::compat
Shell::Parser
Mac::Resources
Win32::ODBC
Cisco::Reconfig
Net::Hotline
Locale::Maketext::Lexicon
CGI::SSI_Parser
Sybase::Xfer
WWW::Search::FirstGov
Pod::XML
Class::Multimethods
CGI::Ex
Mail::GnuPG
RTx::RightsMatrix
Math::Group::Thompson
Net::BitTorrent::LibBTT
Convert::yEnc
OurNet::BBSApp::Sync
Net::P0f
Astro::Misc
DBD::Sprite
Heap::Simple
Getopt::GUI::Long
POE::Component::Client::Ping
Business::PayPal::SDK
Cache::Cache
Tie::File::AsHash
Usage
Tk::FlatCheckbox
MARC::Record
Geo::Caching
RAS::AS5200
Sun::Solaris::Ucred
Config::IniFiles
Python
Excel::Template::Element::Cell::AutoSize
Encode::UTR22
Speech::Recognizer::SPX
Business::OnlinePayment::Moneris
AppleII::Disk
Games::Dissociate
Net::ICQ
SWIFT::Factory::Tag::Tag21
HTML::Tabulate
CGI::Application::Plugin::DevPopup
Sendmail::Milter
Data::Form::Elements
MMDS
Convert::GeekCode
Embedix::DB
Net::eBay
Net::DRI
Postgres::Handler
X::Osd
PDL::Meschach
HTML::CalendarMonth
LockFile::Simple
Unicode::Lite
GMail::IMAPD
Win32::File::Summary
Ogg::Vorbis::Header
Math::Symbolic::Custom::CCompiler
Bundle::Test
Data::Compare
DBD::Sqlflex
Mac::iTunes
Test::MockRandom
Net::XWhois
RPM::Database
Mac::Macbinary
Tk::Statusbar
Tk::IconCanvas
Math::Approx
Win32::EventLog::Carp
Net::LDAPapi
Date:Jalali
Finance::Performance::Calc
Whitespace
Pod::Rtf
Geo::ShapeFile
Persistent::mSQL
Image::GD::Thumbnail
IPChains::PortFW
Graph::Writer::Dot
Finance::Amortization
Weather::NOAA::GFS
SQL::Statement
HTML::BarChart
Algorithm::Networksort
AFS::Command
BnP
Net::Telnet
List::MRU
Mail::Procmail
Class::Template
Persistent::Sybase
Crypt::Schnorr::AuthSign
Net::NNTP
Lemonldap::Portal::Authntsso
DBIx::SystemCatalog
Protect
PostScript::Basic
Regexp::Assemble
HTML::Widgets::Search
Tie::LDAP
Net::DNS::Zone::Parser
Astro::MoonPhase
ExtUtils::F77
PostScript::Document
DFA::Command
Tree::Menu
Data::RandomPerson
Devel::PerlySense
Business::OnlinePayment
Time::CTime
Math::Bezier
VMS::Priv
Business::GestPayCrypt
Win32::AD::Control::DirSync
File::Spec
Data::Locations
Algorithm::Cluster
CGI::Application::PhotoGallery
Lemonldap::Portal::Standard
Business::UPC
Cache::Repository
DFA::Kleene
Mac::PropertyList
Convert::RACE
PHP::Include
PerlIO::via::CBC
Mail::MH
Encode::Detect::Detector
Crypt::OpenPGP
News::NNTPClient
Net::ICQ::On
DB2::db
Wx
Win32::Console
Time::Timezone
Image::Kimdaba
Bundle::BDFOY
Fortran::Format
Net::OpenSoundControl
Net::QMQP
Data::Reporter
Db::DFC
BBCode::Parser
SOOP
Tk::TiedListbox
Lingua::EN::Nickname
DBI
XML::Registry
Math::VectorReal
HTML::FromANSI
Curses
CGI::Query
Win32::UTCFileTime
PostScript::File
Business::WorldPay::Junior
Filter::Trigraph
C::Include
IO::Scalar
HTML::Info
Lingua::Preferred
URI::Escape
Math::Trig
Net::OSCAR
UDDI
Inline::CPP
Business::ISSN
Benchmark::Forking
Date::Simple
Algorithm::ScheduledPath
MRTG::Parse
RAS::HiPerARC
GD::Image::AnimatedGif
Attribute::Handlers
Module::Optional
ExtUtils::configPL
Imager
Smirch
Set::Scalar
Term::Interact
Bio::SAGE
Symbol::Approx::Sub
Synergy
Object::POOF
FameHLI
Parse::ePerl
XML::Catalog
Win32::GUID
Crypt::Shark
Lingua::ZH::Keywords
NexTrieve::UTF8
Tk::Splashscreen
Set::CheckList
Tk::Date
Image::Grab
Image::Xbm2bmp
Text::Affixes
WWW::Yandex::TIC
MIDI::Praxis::Variation
SQL::Abstract
Net::ICQV5
Language::Prolog::Yaswi
Sys::Sysconf
Math::Logic::Predicate
Mail::SRS
SMIMEUtil
Sybase::Sybperl
Test::ISBN
Be::Attribute
Lingua::EN::Namegame
WebSphere::Payment
DBD::PgPP
Algorithm::Pair::Best
NetPacket::TCP
Tk::Columns
Sub::DeferredPartial
Physics::Solar::VSO
Language::DATR::DATR2XML
Time::Format
Java::Swing
Math::Interpolate
ARS
Pod::Select
Lingua::ZH::Toke
Math::Symbolic
Event
Encode::Detect
DBA::Backup
FreezeThaw
IPC::Locker
DB::Table::Row
Tk::Calculator::RPN::HP
HTML::BarGraph
Tk::CollapsableFrame
Db::Documentum
CGI::Panel
NetAddr::IP::Find
File::Wildcard
XML::Handler::PrintEvents
Xmms::Remote
Bundle::Knetrix
Net::Address::Ethernet
MP3::ID3Lib
WWW::Search::Excite
Inline::Java
Excel::Template
BerkeleyDB::Lite
GTop
Graph::Writer::XML
DBIx::Roles
Algorithm::Permute
Heap::Elem::StrRev
Lingua::EN::Cardinal
Astro::Time
Net::DBus
Config::Magic
Devel::Fail::Make
Mail::Client::Yahoo
Sort::Fields
JUNOS
POE::Session
Crypt::Solitaire
Graph::Reader::XML
Physics::Particles
Mysql
PDF::Template
Algorithm::Merge
Games::Baseball::Scorecard
MLDBM::Sync
Math::RPN
Image::Epeg
GD::Image::Orientation
CGI::WebApp
Win32::AbsPath
Mac::SysProfile
Text::Convert::ToImage
TFTP
DCE::UUID
HTML::ActiveLink
PostScript::Resources
Chatbot::Alpha::Syntax
Watchdog::HTTPService
Proc::SafePipe
WWW::Search::Lycos
Linux::Cpuinfo
Router::LG
Alias
Tcl
String::Multibyte
Tie::Assert
Parse::Tokens
Class::Tangram
CORBA::XPIDL
Religion::Package
Embedix::ECD
Mac::Gestalt
HTML::Lint
Heap::Elem::RefRev
Geo::Projection
PCL::Simple
CGI::WML
Class::DBI::Plugin::DeepAbstractSearchPager
Pod::Pdf
Tk
Win32::File::VersionInfo
File::Copy::Link
DBD::Pg
HTML::LoL
Date::Roman
Cache::FastMemoryCache
VMS::Persona
Device::WxM2
Text::xSV
MP3::Daemon
ex::implements
File::Temp
HTTP::Proxy
Tie::TextDir
Iterator::Misc
Locale::MakePhrase
Convert::PEM
Heap::Simple::XS
Pogo
Games::Dice::Probability
C::DynaLib
WWW::Robot
DBIx::Copy
Devel::TraceLoad
Audio::SoundFile
Net::USPS
Mail::Folder
POE::Loop::Glib
PPM::Make
Module::Use
VMS::Fileutils::SafeName
Digest::MD5
Tk::ApplicationNest
Physics::Springs::Friction
Class::PseudoHash
IPC::LDT
Attribute::TieClasses
Tk::LockDisplay
MIDI
String::Parity
Devel::Modlist
Math::Nocarry
Parallel::Pvm
Tk::ObjScanner
Object::Info
File::LckPwdF
Continuus
Concurrent
Term::Prompt
Math::Orthonormalize
Test::Fixme
Tk::FireButton
Log::Dispatch::Jabber
POE::Component::Client::TCPMulti
OS2::FTP
Devel::Constants
List::Intersperse
Thread::Barrier
Authen::ACE
POE::Kernel
WebService::BabelFish
Calendar::CSA
Image::Magick
Text::Tokenizer
Net::DNS
WWW::Search::Ebay
Template::Plugin::Lingua::EN::Inflect
URI::Bookmarks
CGI::Getopt
Env::Bash
Getopt::EvaP
Mail::MboxParser
Text::Refer
DBIx::DBSchema
Tk::FileDialog
POE::Component::Enc::Ogg
Tk::DatePick
Tk::Cloth
Term::Gnuplot
Win32::OLE
Class::GAPI
WWW::Cache::Google
Carp::Datum
Devel::DumpStack
Bundle::KohaSupport
Lingua::EO::Supersignoj
File::Glob
HTML::Bricks
Glib
IMAP::Client
Tie::Plural::Scalar
String::Util
Win32::Exchange::Mailbox
Solaris::InstallDB
POE::Session::GladeXML
Search::InvertedIndex
Crypt::OpenSSL::Random
Convert::Morse
Image::WorldMap
Inline::Struct
Proc::ParallelLoop
CGI::LogCarp
Win32::ADO
CGI::ContactForm
Data::Flow
Date::Parse
Data::Diff
Mac::Files
File::Cache
Parse::Lexer
PerlIO
Net::SSH::Perl
DBD::XBase
Config::Sofu
Object::Mediator
Net::SNMP
HTML::Demoroniser
NexTrieve::Collection
XML::Simple
Math::Geometry::Planar
Schedule::ByClock
String::RexxParse
NexTrieve::Querylog
Tie::ListKeyedHash
Convert::Wiki
Lexical::Typeglob
Digest::Haval256
Text::Beautify
CGI::Echo
Paper::Specs
AI::NNFlex
Text::Starfish
Inline::CPR
DBIx::Browse
Algorithm::SkipList
Proxy::Tk
Term::Visual
Tie::DB_FileLock
CPAN
File::MultiTail
Games::SGF::Tournament
Net::TL1
Crypt::Passwd
Devel::SearchINC
CDB_File::BiIndex::Generator
Text::Table
Mail::POP3Client
Blatte::Ws
Solaris::Contents
Log::Agent
Config::Scoped
HTML::Macro
Mail::Freshmeat
Palm::Magellan::NavCompanion
Time::Zone
RFID::Matrics
Config::General
Class::Unique
Mon::Client
POE::Component::Client::SMTP
Text::Macros
Algorithm::CurveFit
Chart::Base
Gnome2
IO::Zlib
Nmap::Scanner
Math::BigRat
VMS::Queue
MonetDB::CLI::MapiXS
SGI::FAM
DBD::mysql
Solaris::Lgrp
Cdk
Acme::Scripticide
Tie::Array::Huge
CPAN::AutoINC
Mail::Audit
Finance::Bank::CreateCard
Gnome
Filter::Util::Call
Class::StructTemplate
Lingua::EN::Inflect
Lingua::PT::Words2Nums
Win32::GuiTest
PostScript::FontInfo
Tree::Ternary
Object::Transaction
Parse::MediaWikiDump
Verilog::Parser
iCal::Parser
Convert::EBCDIC
Conjury::Core
Mail::GPG
CGI::Application::GDGraph::lines_ap
PostScript::Graph::Key
Syntax::Highlight::Universal
Lingua::ManagementSpeak
ObjStore
Roman
CGI::SSI
Tk::MinMaxScale
WWW::Search::RpmFind
CGI::Cache
B::TerseSize
IO::Socket::PortState::cPanel
DBIx::Tree
Danga::Socket
Chart::Pie
Replication::Recall::DBServer
IPC::Filter
Text::FixEOL
Filter::NumberLines
DBD::Informix
IO::Select
Crypt::Keys
Tk::Task
Watchdog::MysqlService
Getopt::Tiny
OODoc
Net::PH
No::Dato
NetPacket::ARP
Class::Handler
Text::iPerl
Tk::Workspace
Oracle::SQLLoader
Set::Bag
CGI::Response
Devel::Size
Oracle::Loader
Audio::DB
Class::MethodMaker
HTML::SimpleLinkExtor
Fortran::NameList
Mac::Memory
IO::Dir::Recursive
Class::TOM
Math::Symbolic::Custom::Pattern
Archive::Cabinet
Gtk2::Ex::Datasheet::DBI
Ace
X11::Xpm
IPC::Run
Hardware::Simulator
Time:Compare
Bit::Vector
CGI::Application
Win32::IPC
Time::Period
Data::ID::Exim
News::Gateway
RPC::Simple
SVG::Template
POE::Component::OSCAR
Data::Describe
MusicBrainz::Client
VCS::StarTeam
Tie::DBI
HTML::ElementTable
Proc::PID::File::Fcntl
Win32::Mutex
SQL::QueryBroker
Sub::Regex
WWW::Webjay
Image::Info
Image::Dot
PHP::Interpreter
Net::SMS::Clickatell
Class::DBI::DB2
Tie::ShadowHash
Date::Discordian
Net::DHCP::Watch
Tk::Tree
HTML::Entities
Project::Gantt
Text::BarGraph
Cz::Sort
Text::Trie
CGI::SecureState
Math::Function::Roots
Finance::Bank::DE::SpardaBank
VRML::Color
CfgTie
Telephony::CountryDialingCodes
Class::Tree
Lingua::EN::Infinitive
Games::AIBots
HTML::TagUtil
Encode::Registry
CORBA::Python
Text::Record::Deduper
Heap::Fibonacci
Tie::SecureHash
File::Flock
TeX::DVI
User::Identity
Curses::UI::POE
File::Tail
Async::Group
HTML::Widgets::DateEntry
Net::Patricia
Audio::Moosic
PostScript::Font
Geography::Countries::LatLong
SCUBA::Table::NoDeco
WWW::Mechanize
X11::Lib
Net::Whois
DBD::QBase
WWW::Lunarstorm
Games::WordFind
Test::Cmd
HTTP::SimpleLinkChecker
Color::Scheme
XML::CSV
Oracle::Trigger
IMAP::Admin
XML::GDOME::XSLT
Text::Diff3
Finance::Bank::DE::NetBank
Ratpoison
Gtk2::SourceView
Server::Server::EventDriven
Win32::Process
Class::ISA
HTTP::Request::Form
Attribute::Signature
Class::Prototyped
Math::BooleanEval
YAML
Term::ScreenColor
Tk::TreeGraph
Mac::OSA::Simple
SNMP::BridgeQuery
Perl6::Subs
Resources
Text::ScriptTemplate
Tk::Pane
Argv
Term::Twiddle
AI::Fuzzy
Mail::Send
HTML::Table
Config::FreeForm
IPC::Shm::Simple
Net::CDP
Sun::Solaris::Privilege
Crypt::NULL
Module::MakeDist
PDL::Slatec
Find::File::Object
POE::Component::Daemon::Win32
Clips
Statistics::CalinskiHarabasz
IP::Anonymous
PostScript::Graph::XY
Archive::Tar::Stream
CGI::MultiValuedHash
PDA::Pilot
Hook::PrePostCall
Test::Litmus
HTTP::Cookies::Safari
Image::WMF
Acme::Floral
Digest::MD5::File
HTML::Stripper
HtDig
Data::SecsPack
X11::XEvent
Math::Polyhedra
Class::Accessor
Mac::Errors
define
Acme::Buffy
WML::Card
MIME::Base64
Set::IntRange
Text::Vpp
DBIx::HTML::LinkedMenus
Filesys::SamFS
Astro::Cosmology
Mail::DSN
DCE::RPC
Acme::Enc
WebService::GoogleMaps
Workflow
Sort::Key
Finance::Shares::Chart
Puppet::Any
DateTime::Format::Strptime
IPTables::IPv4::IPQueue
Rose::DB::Object
DBIx::Table
Tie::Dir
Data::HexDump
Term::ReadKey
Tuxedo
Catalog
Business::AU::TFN
String::CRC32
Tie::RangeHash
HTML::Chunks::Local
HTML::Encoding
PostScript::Graph::Paper
HTML::Diff
NexTrieve::DBI
Tk::ProgressBar::Mac
CGI::Session::DB2
Chart::Plot
MP3::M3U
HTML::FormTemplate
Class::DBI::Plugin::Pager
DB_File::DB_Database
Math::Random::Brownian
Log::Detect
Teradata::BTET
Games::AlphaBeta
Mail::Vacation
Thesaurus
Win32::Console::ANSI
Mac::Notification
XML::GDOME
Getopt::ArgvFile
Oracle::DML
Conjury::Stage
Archie
Include
MLDBM::TinyDB
Net::Jabber
X11::Xforms
Finance::Bank::Wachovia
B::Deobfuscate
DBIx::CodeKit
Image::Imlib2
Inline::Tcl
Mariachi
DBIx::XHTML_Table
Devel::TraceMethods
Win32API::File::Time
Net::DNS::ValueDomain::DDNS
MPEG::Audio::Frame
Convert::SciEng
Kwiki
WWW::Scrobbler::Stats
Statistics::Descriptive
Date::Gregorian
Net::HTTPTunnel
Number::Encode
Tk::HistEntry
Scalar::Footnote
Test::LectroTest
LWP::Parallel
Crypt::Loki97
Blatte::Parser
Conjury::C
File::Sync
Language::Prolog
Tree::Fat
Tie::HashDefaults
DbFramework::DataModel
HTML::Template
Tie::FileLRUCache
Rose
XBase
DBD::TSM
String::Strip
Tk::RotCanvas
CGI::MxScreen
Tk::NumEntry
Gemstone
Tie::File
SQL::Snippet
Event::Stats
RFID::ISO15693::Tag
OLE::Storage
Net::WWD
Slash
Class::DBI::Oracle
Geo::Coordinates::Convert
HTML::WebMake
Text::Conversation
Lingua::Stem::Snowball::Da
Math::Geometry
Sys::AlarmCall
Crypt::Khazad
Devel::FindGlobals
File::Copy
Test::File
Win32::SqlServer
Term::Size::Heuristic
WWW::Pipeline
Algorithm::LUHN
File::Copy::Recursive
IO::Event
Benchmark::Timer
News::Search
Authen::Krb5::KDB
DBIx::Simple
SWIFT::Factory::Tag::Tag15
File::Tail::App
Relations
Games::Traveller::UWP
MasonX::Resolver::PAR
Data::Tabular
Digest::MD4
HTTP::Recorder
Geo::IP
Text::Templet
Tk::JPEG
Win32::MSAgent
WDDX
Finance::Bank::AU::StGeorge
Net::IP::Match::XS
Language::Befunge
Convert::IBM390
Text::Wigwam
MIME::Head
Log::Check
AppConfig::Std
CGI::SpeedyCGI
IPC::Session
Acme::Void
Text::CSV_XS
Sprite
CDDB
Crypt::SmbHash
Mail::Address
Win32::FUtils
SQL::Generator
DBIx::FileSystem
Convert::Lucene
Time::Elapse
PDL::PP
Statistics::Hartigan
Crypt::Blowfish_PP
Crypt::GCrypt
HTTP::Message
Math::Fortran
NexTrieve::Replay
Lingua::PT::Hyphenate
Digest::BubbleBabble
Math::Project3D::Plot
XML::STX
Filter::Crypto
Devel::Cover
File::Stream
Data::Lazy
Lemonldap::NG::Portal
Perl6::Classes
Openview::Message
AI::NeuralNet
Chart::PNGgraph
Encode::EUCJPMS
Text::Templar
DBD::mysqlPP
Parse::Nessus::NBE
DBD::ASAny
Quiz::Question
Getopt::GetArgs
Log::Agent::Logger
DBD::DB2
LWP::RobotUA
IO::React
Math::Pari
Blatte::Syntax
DbFramework::Attribute
Blatte::HTML
ex::caution
PixDraw
Filter::Util::Exec
Myco
Win32::MSI
Mail::SpamAssassin
Sub::Timebound
SVG::Graph
Crypt::PassGen
SVG::Element
Tk::Axis
CGI::Enurl
Mail::Box::Parser::C
Devel::SmallProf
HTML::BBReverse
OS2::UPM
Class::Facade
Net::LibLO
String::Ruby
Authen::CyrusSASL
Time::Warp
Compress::LZW
Tk::DBIx
Text::Netstring
CGI::Minimal
XML::AutoWriter
File::Searcher::Interactive
User::grent
WWW::ImageSpool
RenderMan
Persistence::Object
HTML::EasyTable
Lingua::TH::Segmentation
Time::JulianDateTime
Lingua::EN::AddressParse
Convert::Base
Flickr::Upload
iCal::Parser::HTML
Win32::SharedFileOpen
Time::HiRes
String::CRC
Physics::Springs
ConfigReader::Simple
Emacs::Lisp
BerkeleyDB
Spectrum::CLI
Devel::CallerItem
Finance::NikkeiQuote
XML::Filter::Reindent
Class::ParmList
PostScript::Simple::Table
DBD::CSV
DbFramework::Key
LWP::Protocol::http::SocketUnix
Mail::SPF::Query
Net::DHCPClient
Tk::JComboBox
Parse::Syslog
Heap::Binomial
Voicent
Softref
Convert::ASCII::Armor
Lingua::Zompist::Kebreni
HTTP::GHTTP
Devel::Trampoline
Digest::SHA::PurePerl
Win32::Shortcut
WWW::Search::UrbanDictionary
SQL::Builder
RDF::Redland
HTML::TableLayout
Chart::Pie3d
HTML::Template::Compiled
Proc::Forkfunc
GD::Barcode
Net::LPR
Bio::GMOD
Exporter::PkgAlias
Image::IPTCInfo
Class::Prevayler
Stat::lsMode
Math::Cephes
Attribute::Memoize
Sybase::Simple
GD::Graph
DBD::DtfSQLmac
Net::LDAP
Sun::Solaris::Task
CGI::XMLForm
Business::ISMN
Text::Textile
Acme::Morse::Audible
Lingua::GA::Gramadoir
PDF::Create
HTML::ElementRaw
Number::OutlineNumber
Interface::Param
Object::Trampoline
Net::Hesiod
ControlX10::CM17
Sybase::DBlib
Config::YUM
Wiki::Gateway
Image::DS9
Math::Polynomial
Algorithm::Hamming::Perl
CGI::Authent
URI::OpenURL
Lingua::ZH::HanDetect
Tie::IxHash
FindBin
Net::hostent
CMS::Mediawiki
Win32::Resources
News::Article::NoCeM
HTML::Chunks
Lingua::Zompist::Verdurian
Crypt::OpenSSL::BN
Getopt::Long::File
String::BitCount
Lingua::PT::Nums2Words
Acme::PIA::Export
Sys::PortIO
PDL::IO::HDF5
Gedcom
CGI::QuickForm
MP3::M3U::Parser
MPEG::MP3Play
RT
Image::ExifTool
SGML::Entity
DBD::ODBC
File::Sort
XML::Writer::String
VMS::Process
Date::Language
Pod::Usage
IPC::XPA
WWW::Sucksub::Divxstation
VMS::ICC
Crypt::Misty1
Net::Gnutella
WWW::Search::ISBNDB
Gtk2::Ex::FormFactory
XML::miniXQL
HTTP::Headers
Spreadsheet::WriteExcel::Worksheet::SheetProtection
Chemistry::Elements
I18N::LangTags
List::Compare
Net::Mac::Vendor
Games::Crosswords
DBIx::MSSQLReporter
Log::Topics
IO::NestedCapture
RFID::Base
Net::SSH
HTML::Element
Tk::Pod
Tie::Judy
Devel::Fail::MakeTest
B::Size
Games::Dice
Simulation::Automate
Festival::Client::Async
Compress::Bzip2
Devel::Messenger
Graphics::ColorNames
Language::Ook
Lingua::EN::Hyphenate
Win32::RemoteTOD
Text::Merge
POE::Component::Client::UserAgent
Getopt::Regex
Lingua::EN::NameCase
XML::Parser
Crypt::UnixCrypt
Graph::Writer
iCal::Parser::SAX
Cz::Cstocs
Math::Random::MT
XML::Edifact
Class::Singleton
Decision::Markov
SWIFT::Factory::Tag::Tag17A
HTML::Tagset
CGI::Imagemap
WWW::Blog::Identify
Rosetta
Lingua::EN::Syllable
MIME::Parser
Attribute::Deprecated
Data::Variant
Device::ParallelPort
Test::Reporter
Math::Geometry::GPC
XML::XPath
POE::Component::MPG123
XML::Handler::Trees
Geo::IP2Location
Net::CyanChat
Algorithm::SixDegrees
Lemonldap::NG::Handler
Datascope
SNMP::Monitor
Text::StripAccents
NexTrieve::Document
Verilog::GetInfo
Class::DBI::Plugin::DeepAbstractSearch
HTML::Parser
Audio::File
HTML::TableExtract
Time::Avail
PDL::NetCDF
WWW::Search::Yahoo
Log::Localized
Net::SSL
Net::Bind
XML::Validator::RelaxNG
Tk::CheckBox
Gtk::Dialog
Number::Phone::PT
HTML::EasyTags
Clarion
Date::Tolkien::Shire
HTML::LinkExtractor
Math::Libm
SVG::DOM
BizTalk
HTML::ParseBrowser
DBIx::AnyDBD
Tie::Hash::CustomStorage
Audio::FLAC::Decoder
Mail::Header
Devel::Symdump
Log::Accounting::Sendmail
Cache::Mmap
GIFgraph
Convert::UU
Tk::Copy::Mac
Net::EMI::Common
Search::Kinosearch
Net::BGP
Linux::Fuser
Lingua::EN::MatchNames
Locale::Country
DCE::Status
Model3D::WavefrontObject
DBD::ADO
X11::Keysyms
Java::Build
Games::Bingo
Parse::Lex
Gtk2::Ex::DBI
IO::Wrap
Math::VecStat
Set::Crontab
Pod::Readme
Encode::Arabic
String::ShellQuote
SVG
XML::Spew
POE::Component::ControlPort
Unix::Processors
Text::English
FindBin::libs
News::Article
Test::Manifest
Chart::Scientific
Oracle::OCI
Lingua::PT::Stemmer
Physics::Unit
GD::Gauge
Test::MockDBI
Statistics::ChiSquare
NexTrieve::Search
NetAddr::IP
Net::DNS::SEC
UUID
Business::US_Amort
Convert::Binary::C
XML::Tidy
DBIx::FetchLoop
Tie::TransactHash
Devel::Truth_Table
Games::Multiplayer::Manager
Lingua::FeatureSet
Net::IMAP
Win32API::MIDI
Data::Favorites
Device::SerialPort::Xmodem
CGI::CList
PDL::NiceSlice
Penguin::Easy
Params::Validate
Tk::DirSelect
URI::URL
RTx::Shredder
Bio::Genex
POE::Component::Proxy::TCP
Math::Logic
Net::SMS::Genie
Statistics::ConwayLife
DBIx::VersionedSchema
Math::ematica
Math::Calc::Units
Iterator
Date::ICal
Tk::TFrame
POE::Component::SubWrapper
DBIx::Wrapper::Config
Net::ICal
Games::Tournament::BlackJack
Ekahau
XML::Element
CGI::Application::Plugin::Eparam
NexTrieve
Time::Seconds
Pod::Hlp
DBIx::Table2Hash
Pod::MIF
Compress::LZO
WWW::RobotRules
XML::Canonical
Tie::RemoteVar
Tie::SentientHash
XML::Encoding
Pod::Tree
Visio
SWIFT::Factory::Tag::Tag30
Net::Ping::External
Linux::MemInfo
Number::Phone::IE
Font::TTF
Tree::Trie
Template::Plugin::SSI
Socket::PassAccessRights
Tie::Watch
DES
Math::Project3D
Data::Validate::Domain
Devel::Coverage
Boulder
Math::MatrixReal::Ext1
Gtk2::Ex::PopupWindow
File::BasicFlock
BTRIEVE::SAVE
Biblio::Thesaurus
Carp::Assert
Linux::Svgalib
Geo::Distance
DBIx::Chart
MP3::Info
Digest::Elf
Win32::Word::Writer
HTTP::Status
RPC::PlClient
Lingua::Conjunction
HTTP::Webdav
Tk::ComboEntry
IO::Redirect
PDF::API2
DCE::Registry
NetPacket::IGMP
List::Part
Lingua::RU::Charset
SOAP::Clean
Festival::Client
Crypt::Twofish
Statistics::MaxEntropy
Net::DNS::DynDNS
DBIx::glueHTML
Net::DNS::TestNS
Math::Round
File::lockf
XML::PPD
Games::DungeonMaker
DBIx::CGITables
Math::MatrixBool
SWIFT::Factory::BasicHeader
Net::Goofey
XML
DBIx::Transaction
System2
Math::BigInt::BitVect
Tk::FontDialog
Persistent::DBI
XML::Handler::EasyTree::Generator
OurNet::FuzzyIndex
Sys::Uptime
Alzabo
Syntax::Highlight::Perl
WWW::Bookmarks
NexTrieve::Resource
CGI::Application::Plugin::HtmlTidy
X11::XFontStruct
App::Config
Mail::Box
File::BSDGlob
Crypt::Rijndael_PP
Linux::Inotify
Data::Postponed
Business::OnlinePayment::WorldPay::Junior
HPUX::SDUX
GISI::MIFMID
Win32::API
AI::Pathfinding::AStar
POE::Component::RSS
VMS::Monitor
WWW::Google::Video
HTML::Debug
Win32::SystemInfo
Class::Measure
Tangram
LockFile::Manager
Math::Quaternion
Business::OnlinePayment::E2Payments
Regexp::Func
Crypt::CBC
Crypt::CipherSaber
PerlPoint::Package
Set::Object
String::Approx
Win32::Message
Win32::IIS:SMTP
DBIx::XML::DataLoader
Tie::RndHash
Data::TimeSeries
IBM::LoadLeveler
WebFS::FileCopy
Font::FNT
Mail::Vmailmgr
Filter::sh
Win32::GUI::Carp
Oak
Puppet::Log
Orac
Curses::Forms
Net::IDN::Encode
Tie::iCal
File::Find::Rule::XPath
Crypt::UnixCrypt_XS
Time::Piece::DB2
AudioCD
Test::MultiFork
Net::Daemon
X11::FreeDesktop::DesktopEntry
Math::BaseCalc
DBIx::TableAdapter
IPC::SharedCache
Tk::MatchEntry
Tk::Thumbnail
XML::DT
Tie::Hash::MultiValue
Class::Loader
Term::VT102
PV
HPUX::Pstat
RAS::PortMaster
Filter::Simple
Win32::NetAdmin
XML::OPML
Unicode::Japanese
AI::Gene::Simple
Bio::MAGE
Widget::FixedWidthFont::Input
SWIFT::Factory::ApplicationHeader
GD::Barcode::Code93
Prima
Set::NestedGroups
HTTP::Cookies::Find
Net::Peep
RADIUS::UserFile
URI::Attr
Iterator::Util
Archive::Chm
Acme::Pythonic
DNS::ZoneParse
CORBA::IOP::IOR
Math::ConvexHull
Date::Simple::Month
NexTrieve::Targz
Win32::SoundRec
DateTime::Format::Pg
HTML::Processor
HTML::ElementGlob
Class::Flyweight
Text::Shift
XML::RSS::FOXSports
NetPacket::UDP
Net::Vypress::Chat
MP4::Info
DBIx::Password
WWW::TVguide::NL
RPM
HTTP::Request::Common
CGI::Lite
UML::Sequence
BBDB
Math::Business::EMA
Expect
WWW::Postini
Finance::SE::PPM
Regexp::Shellish
Net::SDP
Text::Cipher
String::Edit
Lingua::Tolkien::BURL
Tie::OffsetArray
No::KontoNr
POSIX::SchedYield
Rose::Object
Data::Random
Thread::RWLock
Device::ISDN::OCLM
Rose::URI
Net::Time
Genezzo
Mobile::UserAgent
Net::AudioScrobbler
Win32::RASE
IPC::Cache
AtExit
AxKit::XSP::BasicSession
Term::EditLine
Silly::Werder
Taint
Lingua::EN::Squeeze
Business::Payroll::AU::PAYG
Template::Plugin::HTML::BBCode
Text::German
PerlIO::gzip
Proc::Short
RDF::Service
SQL::Routine
ETL::Pequel
XML::Parser::Wrapper
Algorithm::Munkres
Test::MockClass
DBIx::OracleSequence
Callback
File::Repl
Fax::DataFax
DBIx::XMLMEssage
Win32::Semaphore
Regexp::Tr
Tk::Autoscroll
IO::Multiplex
Spreadsheet::ParseExcel
Compress::Zlib
Compress::PPMd
XML::Dumper
Audio::Ecasound
Unicode::MapUTF8
DB_File::Lock
CGI::Screen
Test::FIT
DBIx::Recordset
Tk::Carp
Tk::TabbedForm
VRML::Base
Image::Timeline
Time::Unix
VMS::Lock
P4::Client
Locale::PO
Win32::DriveInfo
Mac::Spotlight
POE::Component::Client::HTTP
WWW::Sucksub::Vostfree
SNMP
WWW::Search::Magellan
Tk::autobind
Math::CDF
DBZ_File
MasonX::Resolver::CVS
Tie::Concurrent
Lingua::Zompist::Barakhinei
Tk::Separator
Net::SMTP
Oracle::Sqlldr
Logfile
CGI::Persistent
Log::TraceMessages
NetServer::Generic
Palm::SMS
Guile
Audio::MikMod
Digest::SHA
Locale::Currency
CGI::Test
DBD::Sybase
Text::TagTemplate
Net::Whois::RIPE
Crypt::SEAL2
Class::Classless::DBI
Regexp::Extended
File::Searcher::Similars
DBIx::HTML::PopupRadio
Class::Closure
Lingua::JA::Sort::JIS
Lingua::PT::UnConjugate
Wais
Class::DBI::Loader::DB2
Mail::IMAPClient
Crypt::DSA
Mail::Ezmlm
Mac::AppleEvents
Inline::ASM
HTTP::Negotiate
Filesys::Df
Msql
Time::TAI64
Metadata::SOIF
Tk::Stderr
Mail::Field::Received
Net::ParseWhois
List::Comprehensions
File::Split
Blatte::Compiler
SVG::XML
Image::DeAnim
Tree::Nary
Math::SimpleInterest
AnyData
Mail::Field
Persistent::Oracle
Test::Portability::Files
DBD::Illustra
Crypt::Rabbit
CGI::Explorer
XML::SAX::ExpatXS
XML::Sablotron
FUSE::Client
HTML::EP
Lingua::Ispell
SNMP::NPAdmin
Class::XPath
Sys::CPU
Schedule::At
Getopt::Tabular
R3
XML::UM
DBIx::TextIndex
Tk::TOTD
Inline::Python
Win32::ASP
MSDOS::SysCalls
File::Backup
Test::PerlTidy
XML::LibXML
Test::Files
Class::Driver
XML::Mini
Mac::Glue
PGP
Test::Version
DCE::DFS
Net::SNPP
Term::Activity
HTML::Simple
Algorithm::Diff
ORM
SNMP::Util
Net::DHCP
Curses::Widgets
Bloom::Filter
Net::Traceroute
Math::Fractal::DLA
PHP::Session::DB
Math::BigInt::Pari
SyslogScan::SyslogEntry
Test::RandomResults
NexTrieve::Mbox
Win32::Net::Session
Audio::MPD
Math::FresnalZone
EventServer
SGI::FM
HTML::Formulate
Crypt::OpenSSL::PKCS12
Speech::Festival
Tk::ContextHelp
Audio::Mixer
Win32::SAPI5
HTTPD::UserAdmin
Cache::Bounded
Archive::Parity
Net::Pager
Lingua::Stem
B::LexInfo
Text::Ngram
NetCDF
Lingua::AlignmentSet
Authorizenet
Class::DBI::Plugin::CountSearch
HTML::FromText
Math::Business::MACD
Time::UTC
PerlMenu
XML::ASCX12
Authen::Krb5
EB
Astro::Sunrise
POE::Exceptions
OpenOffice::PerlPoint
Audio::MPEG
Log::Delayed
Palm::Memo32
Alarm::Concurrent
Convert::ASN1
SystemC::Parser
Net::iTMS
Getargs::Mixed
GDS2
Number::Format
Inline
Persistent::LDAP
IO::File::Lockable
POE::Component::IRC
GD::Image::Thumbnail
PostScript::ISOLatin1Encoding
Term::Screen
NEXT::init
Mac::Sound
Quantum::Entanglement
Win32::GUI
X11::Protocol
SOAP::Data::ComplexType
DBIx::Abstract
Lingua::PT
Sort::Versions
Text::vCard
WordNet::Similarity::Visual
Metadata::IAFA
Text::Contraction
WordNet::SenseRelate::AllWords
WIN32::MSI::SummaryInfo
Class::DBI
Event::RPC
DBIx::HTML::ClientDB
PostScript::Barcode
WWW::Lyrics
Crypt::SKey
OpenGL
Mac::Speech
Convert::BinHex
Net::Inet
Pod::Index
HTTP::WebTest
MySQL::TableInfo
DBD::Altera
Mail::Mailer
Class::DBI::Storable
Net::UDP
Perl6::Variables
Astro::SpaceTrack
Class::Mutator
Java::JVM::Classfile
MP3::Tag
IO::ScalarArray
Solaris::PerlGcc
Linux::Pid
Nokia::File::NFB
DBD::Excel
Lingua::TR::Hyphenate
Net::SMS::Web
Heap::Elem
Puppet::Body
POE::API::Peek
POE::Component::Growl
Devel::DProf
Class::DBI::mysql
Tie::LLHash
Math::FFT
Math::Expr
Math::Polygon
POE::API::Hooks
MARC::XML
Template::Plugin::StickyQuery
Silly::StringMaths
Stream::Reader
Business::CreditCard
Rose::HTML::Objects
Multimedia::SDP
Tern::Size::Heuristic
NexTrieve::Query
Remedy::ARSTools
HTTP::Cookies::iCab
Win32::StreamNames
Mail::Verify
Set::Array
HTML::Stream
CGI::FormMagick
Class::Translucent
Language::VBParser
Net::FreeDB
Slash::OurNet
Tk::TextANSIColor
SWIFT::Factory::Tag::Tag30V
SystemC::Vregs
Crypt::RandPasswd
Date::ISO
PDF::Report::Table
PostScript::FontMetrics
Net::protoent
Audio::CD
Tk::SlideSwitch
DateTime::Event::Easter
IO::Socket::PortState
CGI::Session::Encrypted
Text::vFile
File::Remove
Template::TagParser
URI::virtual
Geo::Coordinates::Parser
Sys::Filesystem::Solaris
Win32::SerialPort
Mail::DomainKeys
Proc::Queue
Schedule::Match
FileSys::Tree
Net::Printer
Array::PrintCols
VRML
Module::Build
HTTP::Daemon
Perf::ARM
POE::Session::Cascading
Jabber::PubSub::JEAI
Net::AOLIM
Image::Maps::Plot::FromPostcode
Win32::Perfmon
MOP
PostScript::BasicTypesetter
Text::Metaphone
Tibco::Rv
Astro::Constants
Crypt::PGP5
DBIx::Counter
Win32::Event
Drupal::Module::Starter
No::PersonNr
WebService::Upcoming
Math::Matrix
C::Scan
Tie::Scalar::Timeout
Heap::Binary
Text::FillIn
Tk::SignOnDialog
Hash::NoVivify
Pod::Lyx
IO::WrapTie
XML::Twig
HTML::Subtext
CGI::Carp::DebugScreen
Mail::ListDetector
CDB_File::BiIndex
Solaris::Kstat
Crypt::Rainbow
Term::TUI
Tree::Ternary_XS
Object::AutoAccessor
GnuPG::Interface
IPC::Shareable
Convert::DUDE
Tk::DateEntry
Xmms
Getargs::Long
Cisco::Conf
Config::Find
File::Listing
AppleII::ProDOS
Bleach
XML::XSLT
Exception::Cxx
Chatbot::Alpha
Math::Polynomial::Solve
DB::Table
Java
Net::Pcap
Tie::DxHash
Devel::Leak
Tk::Clock
MIME::Lite::TT::Japanese
Text::Query
WWW::Search::Bookmarks
Net::Syslog
Win32::ShellExt
AppConfig
Date::Namedays::Simple
HTTPD::Authen
Filter::CommaEquals
Archive::Ar
Acme::Umlautify
Games::Cards
XML::RSS
SyslogScan::SendmailLine
MSDOS::Descript
Date::Say::Czech
Filter::cpp
VMS::smg
Statistics::ROC
IPC::DirQueue
Yahoo::Search
FCGI
Unicode::UTF8simple
Glade
Bundle::ePortal
Perlbug
CGI::MiniSvr
File::Tabular
Date::Holidays::AU
Text::SpellChecker
Commands::Guarded
Test::Spelling
Crypt::CBCeasy
Parse::Vipar
CGI::Debug
Set::Window
SGI::GL
Net::SAP
Getopt::Simple
News::GnusFilter
SGML::Parser
Mac::Processes
Config::Ini
HTML::Embperl
ExtUtils::ParseXS
Font::Fret
Devel::DebugInit
Unix::UserAdmin
Digest::UserSID
LockFile::Lock
Netscape::Cache
Tie::RegexpHash
Gtk
Time::ParseDate
Search::FreeText
RADIUS::Packet
ToolTalk
fields::aliased
Net::FTP::File
WWW::Yahoo::DrivingDirections
Exporter::Tidy
WordNet::Similarity
HTML::FillInForm
Db::Mediasurface
Net::Subnets
Barcode::Code128
HTTP::Cookies::Omniweb
Filesys::SmbClientParser
Lingua::EN::Ordinal
XML::NamespaceSupport
Sys::Gamin
FAQ::OMatic
Sun::Solaris::Exacct
Heap::Elem::Ref
DBD::AnyData
POE::Component::Server::Syslog
B::Keywords
Win32::WinError
Net::NetSend
Lingua::ZH::PinyinConvert
Class::Inheritance
PDF::FDF::Simple
Sys::Filesystem::Dummy
Module::MakefilePL::Parse
CGI::UploadEasy
Tie::WarnGlobal
Chart::Graph
Net::EPP::Client
SWIFT::Factory::Tag::Tag17U
Tie::Constrained
Class::WhiteHole
Tk::HTML
CGI::Validate
PDF::ReportWriter
Perl6::Parameters
RTF::Generator
Email::Find
Audio::TagLib
Devel::DebugAPI
Algorithm::Knapsack
Text::Balanced
Filesys::Statvfs
PHP::MySQL_Session
X11::Toolkit
Zeta
PGP::Sign
Pod::HTML2Pod
MonetDB::CLI::MapiLib
Date::Holidays::PT
Authen::Krb5::Easy
Convert::Bencode
MSSQL::DBlib
Tie::Simple
Math::BigInteger
GraphViz
GD::Text
Class::ParamParser
Class::Data::Reloadable
HTTP::DAV
Proc::times
Syntax::Highlight::HTML
Math::MPFR
IO::AtomicFile
Mail::VersionTracker
Data::Dumper::HTML
Netscape::History
Tk::More
Proc::Fork
Graph
Tk::XMLViewer
Crypt::GPG
Ioctl
SQL::Schema
File::LinearRaid
Encode::TECkit
LWP::Simple
Attribute::Property
Acme::Tpyo
X11::XRT
Perl6::Doc
DBIx::Interpolate
HTML::DragAndDrop
AI::ExpertSystem::Simple
LWP::UserAgent
HTTP::Client
DateTime::Event::Cron
Language::Prolog::Types
Qt
Games::Sequential
WML::Deck
DCE::ACL
Lemonolap
QWizard
Image::Size
Chatbot::Eliza
Astro::Coord
Text::Printf
IO::Default
MIME::Entity
Mac::AppleScript::Glue
App::Modular
ePortal
Tie::Discovery
Env::Modulecmd
NexTrieve::Hitlist
MIME::QuotedPrint
Sun::Solaris::Project
B
Mac::AppleEvents::Simple
X500::DN::Parser
Data::BitMask
Xmms::Config
NetServer::Portal
PostScript::StandardEncoding
IPC::Signal
Font::TFM
Dir::Purge
UML::State
Mozilla::Backup
AxKit::XSP::Sendmail
Test::Pod
Unicode::EastAsianWidth
Gtk2::TrayManager
Lingua::PT::Inflect
Proc::Background
JavaScript
Chatbot::Alpha::Tutorial
WWW::Scraper::ISBN
PAR::WebStart
Verilog::Language
BBDB::Export
CDB_File
Win32::Process::Info
CGI::FormBuilder
GSM::SMS
Acme::Playmate
Graph::Layout::Aesthetic
GD::SecurityImage
File::Size
Lingua::DetectCharset
Crypt::RC4
Math::Telephony::ErlangB
Tk::Graph
WebService::FreeDB
Biblio::Document::Parser
WWW::BBSWatch
Crypt::TEA
SimpleCDB
PDF::Parse
AI::jNeural
IPC::UPDmsg
Win32::SearchPath
Tree::List2Tree
Net::FTP
DBIx::Objects
Tk::FileEntry
Image::Magick::BarChart
RTF::Tokenizer
Tk::Pgplot
CGI_Lite
DbFramework::PrimaryKey
Math::Fleximal
Test::File::Find::Rule
Algorithm::Munkre
Date::Calc
Net::Gen
CAD::Drawing
Net::xAP
Text::Banner
LockFile::Scheme
CGI::Deurl
Crypt::Square
Spreadsheet::ReadSXC
DBD::InterBase
Finance::Streamer
WWW::Extractor
Iterator::IO
App::Options
Error::TryCatch
CGI::PathInfo
Astro::SLA
Win32::Pipe
Math::Gradient
File::Locate
Language::Frink::Eval
Authen::TacacsPlus
SGML::SPGrove
Net::Chat::Daemon
MSDOS::Attrib
Language::XSB
Pod::DocBook
Solaris::Disk::VTOC
Chart::Gdchart
Win32API::CommPort
XMLI
MLDBM
DBIx::SimpleQuery
SQL::Interpolate
Template::Plugin::ASCIITable
Audio::FLAC::Header
DBD::FreeTDS
AltaVista::PerlSDK
Win32::Process::Perf
Lemonldap::Config::Parameters
Digest::Whirlpool
Cisco::IPPhone
Tie::Handle
Tie::Hash::Stack
Test::Number::Delta
PDL::LAPACK
URI::Sequin
Geo::Coordinates::OSGB
Symbol::Values
Data::JavaScript
Win32::Internet
Tk::Multi
Scalar::Properties
DBD::Solid
CGI::Session
Data::Serializer
Ingperl
MQSeries
File::Slurp
Tk::Olwm
DBD::MaxDB
Data::MultiValuedHash
MIME::Types
Net::NIS
Convert::Translit
Cz::Speak
Exception::Class
Slauth
Net::BEEP::Lite
Carp::CheckArgs
XML::Filter::SAXT
Text::EtText
GStreamer
HTTP::CryptoCookie
Math::Brent
OurNet
Math::MagicSquare::Generator
File::Data
Quantum::Usrn
Solaris::ACL
Authen::SASL::Cyrus
XML::Generator
Mac::AssistantFrames
Authen::ACE4
RFID::Alien
Audio::OSS
DBD::SQLrelay
PDF::Report
Win32::Clipboard
Text::Highlight
Language::Prolog::Sugar
Net::ICAP
Net::EMI::Client
DCE::Login
Lingua::Zompist::Cadhinor
DBD::PrimeBase
Date::Format
Tie::Cache::LRU
Term::ReadLine::Perl
Business::NoChex
Tk::Zinc
Array::IntSpan
Object::InsideOut
Mac::Carbon
Tcl::Tk
Chart::XMGR
XML::QL
Finance::Shares::MySQL
Lyrics::Fetcher::Google
Digest::HMAC
NetPacket::Ethernet
Tk::ReportBox
HTML::ElementSuper
Data::Stash
Text::CSV
Term::ANSIScreen
Math::BigIntFast
Data::Walker
Language::Zcode
AI::NeuralNet::Kohonen
Net::ICQV5CD
Solaris::Procfs
VRML::VRML1
Algorithm::SISort
CGI::Untaint::Filenames
Tk::TableEdit
Text::Scraper
Catalyst::Plugin::Authorization::CDBI::GroupToken
MathML::Entities
Class::Classless
File::Spec::Link
Math::Random::MT::Auto
HTTP::Cookies
Algorithm::Numerical::Sample
Games::Go::AGATourn
Graphics::Libplot
File::ManualFlock
Module::ScanDeps
User::Utmp
dTemplate
Lingua::ZH::Numbers
Text::Template
Tie::Array::CustomStorage
Geo::PostalAddress
Convert::Base32
Encode::HanDetect
File::Signature
OzDB
Net::Google
File::NFSLock
Tie::Cvs
Tk::MListbox
Class::IntrospectionMethods
Set::CrossProduct
Sys::Hostname::Long
Lingua::Ident
GD::Image::CopyIFS
IO::String
Splash::DB
Acme::ScriptoPhrenic
Win32::OLE::OPC
FrameMaker::MifTree
Class::Decorator
HTML::Index
PDF::Reuse::Tutorial
Win32::FileOp
Win32::Registry
Mac::OSA
Mail::Transport::Dbx
HTTPD::GroupAdmin
MasonX::Maypole
Linksys::Config
Proc::ProcessTable
Wx::ActiveX
Debug::FaultAutoBT
Mail::vpopmaild
Config::Properties
xDash
Object::Realize::Later
Crypt::Anubis
CGI::Portable
Mon::SNMP
POE::Component::Client::FTP
Xbase
Log::Dispatch::Win32EventLog
Mac::Growl
FrameNet::WordNet::Detour
Math::MatrixReal
File::RandomAccess
Schedule::Load
Net::SFTP
Sx
DBD::Google
Iterator::DBI
IO::Tty
Crypt::Skipjack
Tk::PhotoRotate
Audio::Radio::Sirius
Term::Slang
Tk::IPEntry
VMS::Fileutils::Root
Tie::Mem
LSF::Hosts
Devel::TraceFuncs
XML::SAXDriver::Excel
Net::ICB
Filesys::DiskSpace
Symbol::Table
Text::DelimMatch
Heap::Elem::NumRev
Crypt::Caesar
URI::Bookmark
DBA::Backup::mysql
Tk::ChildNotification
Lingua::Lexicon::IDP
HTTP::DAVServer
Replication::Recall::Server
Chart::Plot::Canvas
Tk::ImageButton
Math::Amoeba
Rcs
Plugin::Installer
ModPerl::PackageRegistry
Tie::Cache
Devel::Peek
PDL::Options
Net::ACAP
Tk::SplitFrame
PDF::Table
Sub::Recursive
File::Format::RIFF
Crypt::ECB
Text::FastTemplate
Time::Stopwatch
Locale::Msgcat
Convert::Recode
Array::Reform
WWW::SherlockSearch
Log::Accounting
Sort::External
TeX::Convert::Image
Tk::Getopt
DBIx::Informix::Perform
WWW::Search::AlltheWeb
BSD::Resource
Regexp::Genex
HTTP::BrowserDetect
XML::Comma
Class::ArrayObjects
Net::CDDBScan
Filter::tee
Text::Scan
Heap::Simple::Perl
Class::Contract
NexTrieve::HTML
Search::Xapian
Bio::Phylo
XML::XForms::Generator
XML::Stream
Cmenu
Log::Agent::Rotate
Tie::PerfectHash
Hints
Cartography::Projection::GCTP
O
Lemonldap::Portal::Cda
Encode::HanConvert
Schedule::Cron
Sparky
Locale::Maketext::Fuzzy
Template
Net::IMAP::Simple
Parse::Nessus::Plugin
DBD::pNET
POE::Component::Pool::Thread
Mac::Serial
CGI::BasePlus
Persistent::Base
WAIT
WWW::NanoRef
Tie::Persistent
Filter::exec
Games::Worms
Xfce4
Win32::Daemon::Simple

=head1 CHANGES

=over

=item 2006.0510 (YYYY.MMDD)

Initial version of: Bundle::Modules::Acme::Everything-2006.0510

This B<L<Bundle::Modules>> component package is in pre-alpha state with hash ordering.

The ordering of listed modules will eventually be prioritized for efficiency and completeness.

Modules commented out of this module list are either I<unstable> or I<stable> in the B<L<Bundle::Modules>> context.

Optimistically, if there are a lot of the modules commented out, then they are I<stable>, and we're listing I<unstable> context.

Optimistically, if there are a few of the modules commented out, then they are I<unstable>, and we're listing I<stable> context.

If you use the command C<B<man Bundle::Modules::Acme::Everything>>, type C<B</#>> to see the commented out modules as they're higlighted for you by B<man>.

=back

=head1 DESCRIPTION

This Bundle package will install all of the modules listed, if they're not commented out of the B<L<Bundle::Modules>> context.

=head1 SEE ALSO

I<L<Bundle::Modules>>, I<L<Bundle::Modules::Unstable>>, I<L<Bundle::Modules::CPAN>>, I<L<Bundle::Modules::CPAN::Unstable>>, I<L<Bundle::Modules::Apache>>, I<L<Bundle::Modules::Apache::Unstable>>, I<L<Bundle::Modules::Acme::Everything::Unstable>>, I<L<Bundle::Modules::Acme::Everything::Unique>>, I<L<Bundle::Modules::Acme::Everything::Unique::Unstable>>

=head1 AUTHORS

Eric R. Meyers E<lt>ermeyers@adelphia.netE<gt>

=head1 LICENSE for http://www.cpan.org/authors/id/E/ER/ERMEYERS/Bundle-Modules-2006.0519

perl

This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=head1 COPYRIGHT

Copyright (c) 2006 by Eric R. Meyers E<lt>ermeyers@adelphia.netE<gt>


